name: Output event details from issues
on: 
  issues:
    types: [opened]
jobs: 
  output_event: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout 
        uses: actions/checkout@v4
      - name: echo event details
        run: echo "${{ toJSON(github) }}"
